# Generated by Django 3.2.24 on 2024-02-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('order', models.IntegerField()),
                ('publications', models.ManyToManyField(to='publications.Publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
